name: deployment Exercise 1
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: install dependencies
        uses: npm ci
      - name: Lint
        uses: npm run lint
      - name: test
        uses: npm run test
      - name: Build code
        uses: npm run build
      - name: Deploy code
        uses: echo "deploying...""